name: Five Bullet Friday

description: Idea blatantly copied from Tim Ferriss

avatar: https://raw.githubusercontent.com/slouc/slouc.github.io/master/images/profile_pic.jpeg

permalink: /:title/

version: v1.2.0

theme: minima

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'

sass:
  style: :expanded

gems:
  - jekyll-sitemap
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME

markdown: kramdown